### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by Inversion-NL** [Inversion-NL/eu.benext#18]
TypeError: Cannot read property 'toString' of undefined
    at Object.command_report_parser (/drivers/tag_reader_500/driver.js:182:60)
    at CommandClass.<anonymous> (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:538:45)
    at emitThree (events.js:97:13)
    at CommandClass.emit (events.js:175:7)
    at /homey-app/wireless/zwave.js:26:25
    at /homey-app/helpers/client.js:1:1035
    at Array.forEach (native)
    at process.<anonymous> (/homey-app/helpers/client.js:1:1004)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)

**Comment by Inversion-NL** [comment]
@robertraaijmakers could you please take a look?
I receive the crash every now and then.
